<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>send_sms</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <!-- Configure code analysis rules -->
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>ALL</AnalysisMode>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.2" />
    <PackageReference Include="Twilio" Version="7.14.7" />
  </ItemGroup>

</Project>
